galleries:

  "Rooms":
    title: { en: Rooms, de: Zimmer }
    geometries: [ x150, x1000 ]

  "Reception and Resturant":
    title: { en: Reception and Restaurant, de: Reception und Restaurant }
    geometries: [ x150, x1000 ]

  "Around":
    title: { en: Around, de: Around }
    geometries: [ x150, x1000 ]

  "Our Specialities":
    title: { en: Our Specialities, de: Unsere Spezialitäten }
    geometries: [ x150, x1000 ]

  "Swiss Guest House in the Snow":
    title: { en: Swiss Guest House in the Snow, de: Swiss Guest House im Winter }
    geometries: [ x150, x1000 ]
