galleries:

  "Rooms":
    title: { en: Rooms, de: Zimmer }
    geometries: [ x132, 1024x, 1920x ]

  "Reception and Restaurant":
    title: { en: Reception and Restaurant, de: Reception und Restaurant }
    geometries: [ x132, 1024x, 1920x ]

  "Surroundings":
    title: { en: Surroundings, de: Umgebung }
    geometries: [ x132, 1024x, 1920x ]

  "Our Specialities":
    title: { en: Our Specialities, de: Unsere Spezialitäten }
    geometries: [ x132, 1024x, 1920x ]

  "Swiss Guest House in Winter":
    title: { en: Swiss Guest House in Winter, de: Swiss Guest House im Winter }
    geometries: [ x132, 1024x, 1920x ]
