galleries:

  "Rooms":
    title: { en: Rooms, de: Zimmer }
    geometries: [ x150, x1000 ]

  "Reception , resturant":
    title: { en: Reception, Restaurant, de: Reception, Restaurant }
    geometries: [ x150, x1000 ]

  "Around":
    title: { en: Around, de: Around }
    geometries: [ x150, x1000 ]

  "our speciality":
    title: { en: Our specialities, de: Unsere Spezialitäten }
    geometries: [ x150, x1000 ]

  "Swiss hotel in snow":
    title: { en: Swiss hotel in snow, de: Swiss Hotel im Winter }
    geometries: [ x150, x1000 ]
